app = "cv-telegram-bot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[[services]]
  # automatically start machines

  auto_start_machines = false
  # automatically stop machines
  auto_stop_machines = false
  # As telegram bot should run only in one machine
  min_machines_running = 1